create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, role text not null default 'staff' check(role in ('admin','agent','staff')), full_name text, created_at timestamptz not null default now());
create table if not exists public.properties (id uuid primary key default gen_random_uuid(), title text not null, slug text unique not null, property_id text unique not null, description text not null, price numeric(14,2) not null check(price>=0), purpose text not null check(purpose in ('buy','rent')), property_type text not null, location text not null, address text, area numeric(12,2), bedrooms int default 0, bathrooms int default 0, parking int default 0, furnishing text, amenities text[] default '{}', featured boolean not null default false, status text not null default 'draft' check(status in ('available','sold','rented','draft')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.property_images (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id) on delete cascade, storage_path text not null, public_url text not null, sort_order int not null default 0, is_primary boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.projects (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, description text not null, location text not null, starting_price numeric(14,2), property_types text[] default '{}', amenities text[] default '{}', images text[] default '{}', status text not null default 'draft', featured boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.enquiries (id uuid primary key default gen_random_uuid(), name text not null, phone text not null, email text, property_id uuid references public.properties(id) on delete set null, message text not null, status text not null default 'new' check(status in ('new','contacted','interested','closed')), created_at timestamptz not null default now());
create index if not exists properties_purpose_idx on public.properties(purpose);create index if not exists properties_location_idx on public.properties(location);create index if not exists properties_status_idx on public.properties(status);create index if not exists enquiries_status_idx on public.enquiries(status);
create index if not exists properties_created_at_idx on public.properties(created_at desc);
create index if not exists property_images_property_sort_idx on public.property_images(property_id, sort_order);
create index if not exists projects_created_at_idx on public.projects(created_at desc);
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists properties_set_updated_at on public.properties; create trigger properties_set_updated_at before update on public.properties for each row execute function public.set_updated_at();
create or replace function public.is_admin() returns boolean language sql security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin'); $$;
alter table public.profiles enable row level security;alter table public.properties enable row level security;alter table public.property_images enable row level security;alter table public.projects enable row level security;alter table public.enquiries enable row level security;
drop policy if exists "public read live properties" on public.properties;create policy "public read live properties" on public.properties for select using(status='available');
drop policy if exists "admin manage properties" on public.properties;create policy "admin manage properties" on public.properties for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists "public create enquiries" on public.enquiries;create policy "public create enquiries" on public.enquiries for insert with check(length(trim(name)) between 2 and 100 and length(trim(phone)) between 10 and 20 and length(trim(message)) between 2 and 2000);drop policy if exists "admin read enquiries" on public.enquiries;create policy "admin read enquiries" on public.enquiries for select using(public.is_admin());drop policy if exists "admin update enquiries" on public.enquiries;create policy "admin update enquiries" on public.enquiries for update using(public.is_admin()) with check(public.is_admin());
drop policy if exists "public read images" on public.property_images;create policy "public read images" on public.property_images for select using(true);drop policy if exists "admin manage images" on public.property_images;create policy "admin manage images" on public.property_images for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists "public read projects" on public.projects;create policy "public read projects" on public.projects for select using(status='published');drop policy if exists "admin manage projects" on public.projects;create policy "admin manage projects" on public.projects for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists "self profile" on public.profiles;create policy "self profile" on public.profiles for select using(id=auth.uid());
drop policy if exists "admin update profiles" on public.profiles; create policy "admin update profiles" on public.profiles for update using(public.is_admin()) with check(public.is_admin());
insert into storage.buckets(id,name,public) values('property-images','property-images',true) on conflict(id) do nothing;
drop policy if exists "public view property images" on storage.objects;create policy "public view property images" on storage.objects for select using(bucket_id='property-images');drop policy if exists "admin upload property images" on storage.objects;create policy "admin upload property images" on storage.objects for insert with check(bucket_id='property-images' and public.is_admin());drop policy if exists "admin delete property images" on storage.objects;create policy "admin delete property images" on storage.objects for delete using(bucket_id='property-images' and public.is_admin());
-- After creating your first Auth user, run: -- insert into public.profiles(id,role) values('YOUR-AUTH-USER-UUID','admin');

-- Keep this SQL safe to re-run. Do not expose the Supabase service-role key in the browser.
